export enum auth {
  LOGIN = 'LOGIN',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILURE = 'LOGIN_FAILURE',
  LOGOUT = 'LOGOUT',
}

export enum profile {
  CHANGE_NAME = 'CHANGE_NAME',
  CHANGE_DATE = 'CHANGE_DATE',
  CHANGE_PHOTO = 'CHAGE_PHOTO',
  DELETE_PROFILE_DATA = 'DELETE_PROFILE_DATA',
  APPLY_CHANGES = 'APPLY_CHANGES',
}
