# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :distribute do
  gym(
      scheme: "internship",
      workspace: "internship.xcworkspace",
      silent: true,
      output_name: "file.ipa",
      export_options: {
        method: "ad-hoc",
        signingStyle: "automatic",
      }
    )
   firebase_app_distribution(
            app: "1:362640777440:android:00b4c2b401e1c13099f085",
            testers: "example_tester@gmail.com",
            release_notes: "some changes",
            groups: "debug",
        )
  end
end
