# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

    desc "Lane for distributing app using Firebase App Distributions"
    lane :distribute do
        gradle(task: "clean assembleRelease")
        # submit build to firebase app distribution
        firebase_app_distribution(
            app: "1:362640777440:android:5105d842aafe5e8f99f085",
            testers: "example_tester@gmail.com",
            release_notes: "some changes",
            groups: "debug",
            firebase_cli_path: "/usr/local/lib/node_modules/firebase-tools/lib/bin/firebase.js"
        )
    end
end