name: Distribute on firebase

on:
  push:
    branches: [main]

jobs:
  distribute:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: Install bundle
        run: |
          cd android && gem install bundler:2.2.15
          cd android && bundle update --bundler

      - name: Distribute App
        run: cd android && bundle exec fastlane distribute
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
